### ISSUE TITLE
Pytest - can not run pytest.main() programatically

### ISSUE THREAD

**Issue by TheoRadig** [oracle/graalpython#143]
i am facing an exception when executing pytest.main() on graalpython.

this is my command
`context.eval("python", "pytest.main(['-x', 'MyTest.py'])")`
and thats the error
`org.graalvm.polyglot.PolyglotException: IndexError: list index out of range
    at <python>.get_result (/Library/Java/JavaVirtualMachines/graalvm-ce-java8-20.1.0/Contents/Home/bin/pp20_testing/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py:80)
    at <python>.pytest_cmdline_parse (helpconfig.py:89)
    at <python>._multicall (/Library/Java/JavaVirtualMachines/graalvm-ce-java8-20.1.0/Contents/Home/bin/pp20_testing/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py:203)
    at <python>.<lambda> (/Library/Java/JavaVirtualMachines/graalvm-ce-java8-20.1.0/Contents/Home/bin/pp20_testing/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py:84)
    at <python>._hookexec (/Library/Java/JavaVirtualMachines/graalvm-ce-java8-20.1.0/Contents/Home/bin/pp20_testing/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py:93)
    at <python>.__call__ (/Library/Java/JavaVirtualMachines/graalvm-ce-java8-20.1.0/Contents/Home/bin/pp20_testing/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/hooks.py:286)
    at <python>._prepareconfig (__init__.py:207)
    at <python>.main (__init__.py:58)`

**Comment by janehmueller** [comment]
Adding some more details since I tried to reproduce this issue using the graalpython binary.
I'm running GraalVM CE 20.1.0 (Java 8) on macOS Catalina (10.15.6).

I installed pytest using the following commands:
```
./graalpython -m ginstall install setuptools
./graalpython -m ginstall install pytest
```
Note here that even though I seemingly installed setuptools 41.0.1, I got the following warning when the other dependencies were installed.
```
Installed /Users/janehmueller/.local/lib/python3.8/site-packages/setuptools-41.0.1-py3.8.egg
Processing dependencies for setuptools==41.0.1
Finished processing dependencies for setuptools==41.0.1
setuptools installed successfully
```
```
your setuptools is too old (<12)
setuptools_scm functionality is degraded
```

I used the following project setup:
```
core/utils.py - contains function add that is tested
tests/test_utils.py - contains a testcase with 2 tests (one succeeding and one failing)
```
Running the following works with the normal python3.8:
```python
import pytest                                                                                                                                                                              
pytest.main(['tests'])
```
On graalpython I get the following error:
```
===================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.8.2, pytest-5.1.0, py-1.8.0, pluggy-0.13.1                                                                                                                         
rootdir: /Users/janehmueller/Desktop/masters_thesis/polyglot-test-runner
collected 0 items / 1 errors                                                                                                                                                                  

=========================================================================================== ERRORS ============================================================================================
____________________________________________________________________________ ERROR collecting tests/test_utils.py _____________________________________________________________________________
Module could not be imported, the test could be unsupported by GraalPython
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================================================== 1 error in 7.96s =======================================================================================
<ExitCode.INTERRUPTED: 2>
```

and when running `pytest.main(['tests/test_utils.py'])` (which also works with the normal python 3.8) I got the following error:
```
INTERNALERROR> Traceback (most recent call last):                                                                                                                                              
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/_code/code.py", line 429, in from_current                                         
INTERNALERROR>     def from_current(                                                                                                                                                           
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/config/__init__.py", line 695, in _do_configure                                   
INTERNALERROR>     def _do_configure(self):                                                                                                                                                    
INTERNALERROR>   File "<stdin>", line 1, in <module '<expression>'>                                                                                                                            
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/config/__init__.py", line 77, in main                                             
INTERNALERROR>     return config.hook.pytest_cmdline_main(config=config)                                                                                                                       
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/hooks.py", line 286, in __call__                                                  
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)                                                                                                                   
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 93, in _hookexec                                                
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/main.py", line 228, in pytest_cmdline_main
INTERNALERROR>     return wrap_session(config, _main)
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/main.py", line 211, in wrap_session
INTERNALERROR>     config.notify_exception(excinfo, config.option)
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/config/__init__.py", line 743, in notify_exception
INTERNALERROR>     excrepr = excinfo.getrepr(
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/_code/code.py", line 579, in getrepr
INTERNALERROR>     self.type, self.value, self.traceback[0]._rawentry
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/_code/code.py", line 497, in traceback
INTERNALERROR>     self._traceback = Traceback(self.tb, excinfo=ref(self))
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/_code/code.py", line 294, in __init__
INTERNALERROR>     list.__init__(self, f(tb))
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/_code/code.py", line 292, in f
INTERNALERROR>     cur = cur.tb_next
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/config/__init__.py", line 695, in _do_configure
INTERNALERROR>     def _do_configure(self):
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR> AttributeError: 'module' object has no attribute 'enable'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module '<expression>'>
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/config/__init__.py", line 77, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
AttributeError: 'module' object has no attribute 'enable'
```

Hope this helps!

**Comment by msimacek** [comment]
Hi @janehmueller, I was trying to make a small example like yours and it worked fine with GraalVM 20.2. Could you please try that version?

**Comment by janehmueller** [comment]
Running the following gives the same nondescript error:
```python
import pytest                                                                                                                                                                              
pytest.main(['tests'])
```

```
===================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.8.2, pytest-5.1.0, py-1.8.0, pluggy-0.13.1                                                                                                                         
rootdir: /Users/janehmueller/Desktop/masters_thesis/polyglot-test-runner                                                                                                                       
collected 0 items / 1 errors                                                                                                                                                                   
                                                                                                                                                                                               
=========================================================================================== ERRORS ============================================================================================
____________________________________________________________________________ ERROR collecting tests/test_utils.py _____________________________________________________________________________
Module could not be imported, the test could be unsupported by GraalPython                                                                                                                     
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================================================== 1 error in 4.05s =======================================================================================
<ExitCode.INTERRUPTED: 2>  
```

and running `pytest.main(['tests/test_utils.py'])` gives a different error:
```
INTERNALERROR> Traceback (most recent call last):                                                                                                                                              
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/main.py", line 187, in wrap_session                                               
INTERNALERROR>     config._do_configure()                                                                                                                                                      
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/config/__init__.py", line 700, in _do_configure                                   
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))                                                                                                          
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/hooks.py", line 308, in call_historic                                             
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)                                                                                                                    
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 93, in _hookexec                                                
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)                                                                                                                          
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 84, in <lambda>                                                 
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/faulthandler.py", line 26, in pytest_configure
INTERNALERROR>     faulthandler.enable(file=config.fault_handler_stderr)
INTERNALERROR> AttributeError: module 'faulthandler' has no attribute 'enable'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/config/__init__.py", line 77, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/main.py", line 228, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/main.py", line 223, in wrap_session
    config._ensure_unconfigure()
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/config/__init__.py", line 705, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pluggy-0.13.1-py3.8.egg/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/janehmueller/.local/lib/python3.8/site-packages/pytest-5.1.0-py3.8.egg/_pytest/faulthandler.py", line 51, in pytest_unconfigure
    faulthandler.enable(file=_get_stderr_fileno())
AttributeError: module 'faulthandler' has no attribute 'enable'
```

**Comment by msimacek** [comment]
I cannot exactly reproduce the problem, but I can confirm that the `enable` function it is complaining about is indeed missing. I'll add it and let's see

**Comment by msimacek** [comment]
I added the `enable` function. Could you please retest with the current `master` branch?

**Comment by janehmueller** [comment]
Awesome! That fixed it :) Both commands work as expected now:
```
=================================================================================== test session starts ===================================================================================
platform darwin -- Python 3.8.5, pytest-5.1.0, py-1.8.0, pluggy-0.13.1
rootdir: /Users/janehmueller/Desktop/masters_thesis/polyglot-test-runner
collected 2 items                                                                                                                                                                         

tests/test_utils.py .F                                                                                                                                                              [100%]

======================================================================================== FAILURES =========================================================================================
_________________________________________________________________________________ UtilsTest.test_add_bad __________________________________________________________________________________

self = <tests.test_utils.UtilsTest testMethod=test_add_bad>

>   ???
E   AssertionError

tests/test_utils.py:11: AssertionError
=============================================================================== 1 failed, 1 passed in 1.17s ===============================================================================
<ExitCode.TESTS_FAILED: 1>
```
