### ISSUE TITLE
sys.exception() does not work in 24.1.1

### ISSUE THREAD

**Issue by mwsealey** [oracle/graalpython#467]
Calling sys.exception() in GraalPython 24.1.1 does not work.

This is annoying as the Python docs say it was implemented in Python 3.11 (https://docs.python.org/3/library/sys.html#sys.exception)

Very easily reproduced:

`import sys

try:
    raise NotImplementedError("oops")
except:
    t, e, tb = sys.exc_info()
    print(e == sys.exception())`

Crashes out with:

`Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NotImplementedError: oops

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
AttributeError: module 'sys' has no attribute 'exception'`

**Comment by msimacek** [comment]
Thank you for the report, I'll fix it shortly
