### ISSUE TITLE
Unable to install scipy==1.10.1 on 24.2.0-dev (20240827_2122)

### ISSUE THREAD

**Issue by laserjim** [oracle/graalpython#420]
Looks like there is a regression such that `graalpy -m pip install scipy==1.10.1 --no-cache-dir` fails on graalpy `24.2.0-dev-20240827_2122` (latest version available).  It successfully installs on `graalpy-jvm-24.1.0-ea.23` which was released prior to `24.2.0-dev-20240827_2122`.

Failure message is:
```
      [1215/1524] Generating scipy/interpolate/_rbfinterp_pythran with a custom command
      FAILED: scipy/interpolate/_rbfinterp_pythran.cpp
      /tmp/pip-build-env-qdx8g040/overlay/bin/pythran -E ../scipy/interpolate/_rbfinterp_pythran.py -o scipy/interpolate/_rbfinterp_pythran.cpp
      WARNING: Overriding pythran description with argspec information for: numpy.arange
      WARNING: Overriding pythran description with argspec information for: numpy.array
      WARNING: Overriding pythran description with argspec information for: numpy.concatenate
      WARNING: Overriding pythran description with argspec information for: numpy.empty
      WARNING: Overriding pythran description with argspec information for: numpy.empty_like
      WARNING: Overriding pythran description with argspec information for: numpy.fromiter
      WARNING: Overriding pythran description with argspec information for: numpy.fromfile
      WARNING: Overriding pythran description with argspec information for: numpy.random.binomial
      WARNING: Overriding pythran description with argspec information for: numpy.random.bytes
      WARNING: Overriding pythran description with argspec information for: numpy.random.chisquare
      WARNING: Overriding pythran description with argspec information for: numpy.random.choice
      WARNING: Overriding pythran description with argspec information for: numpy.random.dirichlet
      WARNING: Overriding pythran description with argspec information for: numpy.random.exponential
      WARNING: Overriding pythran description with argspec information for: numpy.random.f
      WARNING: Overriding pythran description with argspec information for: numpy.random.gamma
      WARNING: Overriding pythran description with argspec information for: numpy.random.geometric
      WARNING: Overriding pythran description with argspec information for: numpy.random.pareto
      WARNING: Overriding pythran description with argspec information for: numpy.random.gumbel
      WARNING: Overriding pythran description with argspec information for: numpy.random.poisson
      WARNING: Overriding pythran description with argspec information for: numpy.random.negative_binomial
      WARNING: Overriding pythran description with argspec information for: numpy.random.normal
      WARNING: Overriding pythran description with argspec information for: numpy.random.laplace
      WARNING: Overriding pythran description with argspec information for: numpy.random.logistic
      WARNING: Overriding pythran description with argspec information for: numpy.random.lognormal
      WARNING: Overriding pythran description with argspec information for: numpy.random.logseries
      WARNING: Overriding pythran description with argspec information for: numpy.random.power
      WARNING: Overriding pythran description with argspec information for: numpy.random.ranf
      WARNING: Overriding pythran description with argspec information for: numpy.random.randint
      WARNING: Overriding pythran description with argspec information for: numpy.random.random
      WARNING: Overriding pythran description with argspec information for: numpy.random.random_integers
      WARNING: Overriding pythran description with argspec information for: numpy.random.random_sample
      WARNING: Overriding pythran description with argspec information for: numpy.random.rayleigh
      WARNING: Overriding pythran description with argspec information for: numpy.random.sample
      WARNING: Overriding pythran description with argspec information for: numpy.random.standard_exponential
      WARNING: Overriding pythran description with argspec information for: numpy.random.standard_gamma
      WARNING: Overriding pythran description with argspec information for: numpy.random.standard_normal
      WARNING: Overriding pythran description with argspec information for: numpy.random.uniform
      WARNING: Overriding pythran description with argspec information for: numpy.random.weibull
      WARNING: Overriding pythran description with argspec information for: numpy.zeros
      CRITICAL: I am in trouble. Your input file does not seem to match Pythran's constraints...
      ../scipy/interpolate/_rbfinterp_pythran.py:81:10 error: function uses an unknown (or unsupported) keyword argument `dtype`
      ----
          out = np.empty((x.shape[0], x.shape[0]), dtype=float)
                ^~~~ (o_0)
      ----
```

**Comment by laserjim** [comment]
A temporary workaround while we're waiting for a real fix is to set the variable `SCIPY_USE_PYTHRAN=0`, which allows the package to install.

**Comment by msimacek** [comment]
Hi @laserjim, sorry about that, it was a regression and I already fixed it last week in 2a8dfda56f32371400b446808481ef5f7a50bddb

**Comment by laserjim** [comment]
Ah, great, thank you!
